spring.application.name=car-repair
server.port=9081

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/car-repair
spring.datasource.username=postgres
spring.datasource.password=12345678

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Serialização JSON: ignora campos nulos na resposta
spring.jackson.default-property-inclusion=non_null
